[[languages.nim.environments]]
compile_to = "cpp"
NIMFLAGS = ["--warnings:on", "--opt:speed", "--mm:refc", "-d:release"]
#NIMFLAGS = ["--warnings:on", "--opt:speed", "--mm:orc", "-d:release"]
[[languages.nim.environments]]
compile_to = "cpp"
#NIMFLAGS = ["--warnings:on", "--opt:speed", "--mm:orc", "-d:release", "--deepcopy:on"]
NIMFLAGS = ["--warnings:on", "--opt:speed", "--mm:orc", "-d:release"]
